name: Fly Deploy
on:
  push:
    branches:
      - master    # change to main if needed
      jobs:
        docker-build:
          name: Build & pubish Docker images
          runs-on: ubuntu-latest
          steps:
          - name: Checkout repo
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
                    
          # This step creates real Sentry releases for the action itself:
          # https://sentry-ecosystem.sentry.io/releases/?project=6576594
          - name: Sentry Release
            uses: getsentry/action-release@v1
            env:
              SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              SENTRY_LOG_LEVEL: debug
            with:
              environment: 'production'
              ignore_missing: true